package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

import java.util.List;

@Repository
public interface CustomerRepository extends JpaRepository<Customer, Long> {

    // Query inferred from method name, code generated by Spring Framework
    Customer findByFirstName(String firstName);

    // JPQL query
    @Query("from Customer c where c.firstName = :name or c.lastName = :name")
    Customer findByNameJpql(@Param("name") String name);

    // JPQL query with join (assuming there is an 'addresses' field in the Customer entity)
    @Query("select c from Customer c join c.addresses addr where c.firstName = :name or c.lastName = :name")
    Customer findByNameWithAddressJpql(@Param("name") String name);

    // Native SQL query (validity not checked, invalid SQL will cause runtime exception)
    @Query(value = "select * from customer as c where c.first_name = :name or c.last_name = :name", nativeQuery = true)
    Customer findByNameSql(@Param("name") String name);

    @Modifying
    @Query("update Customer c set c.firstName = :newName where c.firstName = :oldName")
    void updateName(@Param("oldName") String oldName, @Param("newName") String newName);

    // Custom query to find customers by age
    List<Customer> findByAgeGreaterThan(int age);

    // Add more custom queries based on your requirements

}
