package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

import java.util.List;

@Repository
public interface EmployeeRepository extends JpaRepository<Supplier, Long> {

    // Query inferred from method name, code generated by Spring Framework
    Employee findByName(String name);

    // JPQL query
    @Query("from Employee s where s.name = :name")
    Employee findByNameJpql(@Param("name") String name);


    // Add more custom queries based on your requirements

}
