package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

import java.util.List;

@Repository
public interface ItemRepository extends JpaRepository<Item, Long> {

    // Query inferred from method name, code generated by Spring Framework
    Item findByName(String name);

    // JPQL query
    @Query("from Item i where i.name = :name")
    Item findByNameJpql(@Param("name") String name);

    // JPQL query with join (assuming there is an 'addresses' field in the Customer entity)
    @Query("select i from Item i join i.contract ctr where i.name = :name")
    Item findByNameWithContractsJpql(@Param("name") String name);

    // Native SQL query (validity not checked, invalid SQL will cause runtime exception)
    @Query(value = "select * from item as i where i.name = :name ", nativeQuery = true)
    Item findByNameSql(@Param("name") String name);

    @Modifying
    @Query("update Supplier s set s.name = :newName where s.name = :oldName")
    void updateName(@Param("oldName") String oldName, @Param("newName") String newName);

    // Add more custom queries based on your requirements

}
